tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "peripheryapp/periphery"
tap "signalwire/signalwire"
brew "appledoc"
brew "autoconf"
brew "automake"
brew "bitrise"
brew "carthage"
brew "cmake"
brew "coreutils"
brew "curl"
brew "docker"
brew "docker-machine"
brew "gengetopt"
brew "git"
brew "git-quick-stats"
brew "libffi"
brew "openssl@1.1"
brew "pcre"
brew "readline"
brew "sqlite"
brew "glib"
brew "gnupg"
brew "gradle"
brew "jpeg"
brew "libtiff"
brew "libtool"
brew "imagemagick"
brew "jansson"
brew "ldns"
brew "libconfig"
brew "libmicrohttpd"
brew "libnice"
brew "libogg"
brew "libpq"
brew "libusrsctp"
brew "libwebsockets"
brew "libyaml"
brew "lua"
brew "mas"
brew "node"
brew "node@10"
brew "opus"
brew "pkg-config"
brew "rabbitmq-c"
brew "ruby"
brew "sofia-sip"
brew "speexdsp"
brew "srtp"
brew "telnet"
brew "watchman"
brew "yarn"
brew "yasm"
brew "zlib"
brew "zsh"
brew "zsh-completions"
brew "heroku/brew/heroku"
brew "signalwire/signalwire/flite"
brew "signalwire/signalwire/libks"
brew "signalwire/signalwire/signalwire-c"
cask "adoptopenjdk8"
cask "android-studio"
cask "brave-browser"
cask "docker"
cask "firefox"
cask "gpg-suite"
cask "gray"
cask "intellij-idea-ce"
cask "iterm2"
cask "libreoffice"
cask "libreoffice-language-pack"
cask "mockoon"
cask "periphery"
cask "sketch"
cask "visual-studio-code"
mas "Apple Configurator 2", id: 1037126344
mas "Cinebench", id: 1438772273
mas "Disk Speed Test", id: 425264550
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Kaleidoscope", id: 587512244
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Playgrounds", id: 1496833156
mas "Slack", id: 803453959
mas "Tweetbot", id: 1384080005
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
