#!/bin/zsh

[[ -s "$HOME/.local.env" ]] && source "$HOME/.local.env"

#Brew update
BREW_COMMAND="${BREW_PATH}/bin/brew"
if [ -f "${BREW_COMMAND}" ]; then
	echo "Running brew update" && \
	$BREW_COMMAND "update" && \
	echo "Running brew upgrade" && \
	$BREW_COMMAND "upgrade" && \
	echo "Running brew cleanup" && \
	$BREW_COMMAND "cleanup" "--prune=all"
fi

# bitrise-cli update process
BITRISE_PATH="${BREW_PATH}/bin/bitrise"
if [ -f "${BITRISE_PATH}" ]; then
	echo "Running bitrise plugin update" && \
	$BITRISE_PATH "plugin" "update"
fi

# Oh my ZSH update
OMZ_UPDATE_COMMAND="${HOME}/.oh-my-zsh/tools/upgrade.sh"
if [ -f "${OMZ_UPDATE_COMMAND}" ]; then
	echo "Updating OMZ"
	"$OMZ_UPDATE_COMMAND"
fi

if  [ -x "$(command -v npm)" ]; then
	echo "Updating node global packages"
	npm update -g
fi